FROM python:3.11-slim

WORKDIR /app

COPY scripts/kafka_to_clickhouse.py /app/scripts/kafka_to_clickhouse.py

RUN pip install --no-cache-dir kafka-python==2.0.2 clickhouse-connect

CMD ["python", "/app/scripts/kafka_to_clickhouse.py"]
